module: KituraContracts
author: IBM and Kitura project authors
github_url: https://github.com/Kitura/KituraContracts/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: []

